export const DEPARTMENT_TYPES = {
  INSURANCE: '保険診療',
  SELF_PAY: '自費診療',
  MAINTENANCE: 'メンテナンス',
  HOME_VISIT: '訪問診療',
  RETAIL: '物販',
  OTHER: 'その他',
  TOTAL: '合計',
} as const

export const COST_ITEMS = {
  LABOR: { code: 'LABOR', name: '人件費', isIndirect: true },
  RECEPTION_LABOR: { code: 'RECEPTION_LABOR', name: '受付人件費', isIndirect: true },
  COMMON_STAFF_LABOR: { code: 'COMMON_STAFF_LABOR', name: '共通スタッフ人件費', isIndirect: true },
  LAB_FEE: { code: 'LAB_FEE', name: '技工料', isIndirect: false },
  DIRECT_MATERIAL: { code: 'DIRECT_MATERIAL', name: '直接材料費', isIndirect: false },
  OUTSOURCING: { code: 'OUTSOURCING', name: '外注費', isIndirect: false },
  RENT: { code: 'RENT', name: '家賃', isIndirect: true },
  UTILITIES: { code: 'UTILITIES', name: '水道光熱費', isIndirect: true },
  COMMUNICATION: { code: 'COMMUNICATION', name: '通信費', isIndirect: true },
  LEASE: { code: 'LEASE', name: 'リース料', isIndirect: true },
  SYSTEM_FEE: { code: 'SYSTEM_FEE', name: 'システム利用料', isIndirect: true },
  ADVERTISING: { code: 'ADVERTISING', name: '広告宣伝費', isIndirect: true },
  CONSUMABLES: { code: 'CONSUMABLES', name: '消耗品費', isIndirect: true },
  REPAIR: { code: 'REPAIR', name: '修繕費', isIndirect: true },
  DEPRECIATION: { code: 'DEPRECIATION', name: '減価償却費', isIndirect: true },
  MISCELLANEOUS: { code: 'MISCELLANEOUS', name: '雑費', isIndirect: true },
  OTHER_DIRECT: { code: 'OTHER_DIRECT', name: 'その他直接費', isIndirect: false },
} as const

export const COST_DRIVERS = {
  PATIENT_COUNT: '来院患者数',
  NEW_PATIENT: '新患数',
  RETURN_PATIENT: '再来数',
  APPOINTMENT: '予約件数',
  WORK_HOURS: '勤務時間',
  FTE: 'FTE',
  UNIT_TIME: 'ユニット使用時間',
  UNIT_USAGE: 'ユニット使用回数',
  AREA: '面積',
  REVENUE_RATIO: '売上比率',
  MANUAL: '手動配分率',
} as const

export const CLINIC_TYPES = {
  insurance: '保険中心',
  'self-pay': '自費強化',
  maintenance: 'メンテ重視',
  'home-visit': '訪問あり',
  pediatric: '小児中心',
  general: '総合診療型',
} as const

export const BENCHMARKS = {
  selfPayRatio: 20,
  returnRate: 80,
  cancelRate: 10,
  laborCostRatio: 25,
  materialCostRatio: 8,
  revenuePerUnit: 1500000,
  newPatientsMin: 20,
  maintenanceTransitionRate: 30,
  grossProfitRate: 70,
  operatingProfitRate: 20,
  discontinuedRate: 5,
} as const

export const CSV_MAPPING_LABELS: Record<string, string> = {
  yearMonth: '年月',
  totalRevenue: '総売上',
  insuranceRevenue: '保険売上',
  selfPayRevenue: '自費売上',
  maintenanceRevenue: 'メンテナンス売上',
  homeVisitRevenue: '訪問売上',
  retailRevenue: '物販売上',
  totalPatients: '延患者数',
  uniquePatients: '実患者数',
  newPatients: '新患数',
  returnPatients: '再来患者数',
  maintenancePatients: 'メンテ移行数',
  appointmentCount: '予約数',
  cancelCount: 'キャンセル数',
  noShowCount: '無断キャンセル数',
  insurancePoints: '保険点数',
  laborCost: '人件費',
  materialCost: '材料費',
  labFee: '外注技工費',
  rentCost: '家賃',
  utilitiesCost: '水道光熱費',
  leaseCost: 'リース料',
  depreciationCost: '減価償却費',
  advertisingCost: '広告宣伝費',
  communicationCost: '通信費',
  consumablesCost: '消耗品費',
  insurancePremium: '保険料',
  miscCost: '雑費',
}
